project:
  type: website
  output-dir: docs


website:
  title: "Camille Mazoyer"
  navbar:
    left:
      - href: index.qmd
        text: Home
  google-analytics: "G-F9MPYZJZ47"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
