---
title : Anaconda pour l'oceanographie
---

# Installation de Anaconda

Se réferer à la page [Configurer son ordi Ubuntu pour le calcul scientifique](config_globale_ubuntu.html) pour l'installation de miniconda.


# Création d'un environnement pour l'océanographie

```bash
conda create --name oceano
conda activate oceano
conda install pandas numpy xarray netcdf4 dask scipy ipython jupyter cartopy numba
conda install matplotlib ipykernel cloudpickle tqdm
conda install -c conda-forge xgcm hdf5storage
```

# creation d'un environnement pyferret uniquement

Se référer à la page [Installation de pyferret avec Anaconda](installation_pyferret.html) pour l'installation de pyferret.


# Création d'un environnement oceano et pyferret

Si on veut aussi installer pyferret dans le même environnement, il est conseillé d'intaller pyferret en premier, puis les autres packages: 

```bash
conda create --name FERRET -c conda-forge/label/cf202003 pyferret ferret_datasets --yes
conda activate FERRET
conda install -c conda-forge xgcm hdf5storage xarray 
conda install matplotlib netcdf4 ipython jupyter cartopy numba ipykernel
```

remarque:    
- numpy est installé automatiquement par dépendance de pyferret
- pandas, dask, cloudpickle,  scipy  sont installés automatiquement aussi par dépendances.


# Utilisation de ces environnements 

Pour utiliser cet environnement:
```bash
conda activate oceano
```

Pour désactiver cet environnement lorsqu'on le souhaite:
```bash
conda deactivate
```

remarque: 
- pas d'installation de spyder (incompatibilités, ... si quelqu'un a une solution, je suis preneuse...)

# Installation d'un environnement conda pour Copernicus

Voir la doc [Documentation sur Copernicus Marine](copernicusmarine.html) .

