---
title : Bonnes pratiques de travail 
---


Sous Ubuntu ou Mac

# Utilisation d'un logiciel de mots de passe : KeepassXC  

Il est recommandé d'utiliser un logiciel de mots de passe pour stocker vos mots de passe. Cela permet:

- de ne pas les stocker en clair dans un fichier texte
- de les sécuriser avec un mot de passe principal
- de ne pas réutiliser le même mot de passe sur plusieurs sites : il est facile de recréer de nouveaux mots de passe


## Installation de KeepassXC

Pour installer KeepassXC sous Linux ou Mac, suivre les instructions d'installation sur le site officiel de [KeepassXC](https://keepassxc.org).

## Utilisation de KeepassXC

Pour utiliser KeepassXC, il suffit de créer une base de données de mots de passe et d'y stocker vos mots de passe. Vous pouvez ensuite les copier-coller dans les champs de connexion des sites web. La base de données est sécurisée par un mot de passe principal.
Vous pouvez mettre le fichier de base de données dans un dossier synchronisé avec le service de cloud de l'Osu Pytheas.

# Synchronisation de fichiers avec le service de cloud de l'Osu Pytheas 

Les fichiers importants, tels que les documents (doc, ppt, pdf ..), les scripts non versionnés sous git, peuvent être dans un répertoire de votre ordinateur synchronisé avec le [cloud de l'OSU Pytheas]( https://documentation.osupytheas.fr/?p=3854) (jusqu'à 200 Go). 

# Utilisation de GIT

Il est recommandé d'utiliser git pour versionner vos scripts. Cela permet de garder un historique de vos modifications, de travailler à plusieurs sur les mêmes fichiers et de revenir à une version antérieure si besoin. Voir la [documentation sur git](https://documentation.osupytheas.fr/?s=git) pour plus d'informations. Vos dépôts git peuvent être gérés via le [gitlab de l'osu pytheas](https://gitlab.osupytheas.fr/), le [gitlab de renater](https://services.renater.fr/sourcesup/index), de l'Inria, de l'IRD ...

Les dépôts git ne sont pas à mettre dans le nuage de l'OSU Pytheas, puisque déjà gérés par un serveur git.

