---
title: "Configurer son ordi Mac pour le calcul scientifique"
---

# Installations de logiciels 

Installer les logiciels ci dessous : 

1. [Docker desktop](https://docs.docker.com/desktop/install/mac-install/)

2. [Visual Studio Code](https://code.visualstudio.com/)

3. [Quarto](https://quarto.org/docs/get-started/)

4. [keypassx](https://keepassxc.org)

5. [Terminal](https://github.com/Eugeny/tabby/releases)

6. [XQuartz](https://www.xquartz.org/) pour gérer le serveur X lors de connexions en ssh

# Installation de Anaconda

L'installation se fait via le site officiel d'Anaconda: [Anaconda](https://www.anaconda.com/products/individual).    

Pour certaines installations, par exemple pyferret, il est possible que les packages ne soient pas présents pour l'architecture M3. Pour contourner ce problème, il est possible de forcer l'environnement conda en mode x86_64. Pour cela, il faut installer Rosetta 2 et forcer conda à créer un environnement x86_64.

## 1. Installer Rosetta 2 

Dans un terminal: 
```bash
softwareupdate --install-rosetta
```

## 2. Forcer conda à créer un environnement x86_64 :
Avant de créer et/ou d’installer les packages qui posent problème (PyFerret par ex), définissez la variable d’environnement CONDA_SUBDIR à osx-64 afin de récupérer les paquets compilés pour Intel :

```bash
export CONDA_SUBDIR=osx-64
conda create -n mon_environnement 
conda activate mon_environnement
conda install monpackage
```

Cette manipulation permet à conda d’utiliser les binaires Intel, qui pourront fonctionner via Rosetta 2. Bien sûr, les performances seront moindres qu’une version native, mais cela permet au moins d’utiliser les packages souhaités.


## Installation d'un environnement Anaconda pour PyFerret:

 [Installation de pyferret avec Anaconda](installation_pyferret.html)

# Matlab

- Téléchargement de matlab via le site officiel en créant un compte avec votre email univ-tln.fr. L'installation doit se faire via le wifi ou de chez soi à cause du proxy.

- Pour Luminy, voir [matlab à Luminy](https://documentation.osupytheas.fr/?s=matlab)

# Installation de homebrew

Homebrew est un gestionnaire de paquets pour macOS. Il permet d'installer des commandes du style de linux. Pour l'installer, ouvrir un terminal et taper la commande suivante:
```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
Une fois Brew installé, le mettre à jour avec la commande:
```bash
brew update
```

On peut alors installer des logiciels comme wget:
```bash
brew install wget
```



# Penser aussi à:

- Créer une clef SSH et la diffuser sur d'autres ordinateurs pour éviter de taper son mot de passe (voir doc [Générer une clef ssh](clef_ssh.html) )
